export const REQUEST_MODULE_OPTIONS = [
  "NEW DSD CUSTOMER",
  "NEW FSV CUSTOMER",
  "CUSTOMER SUPPRESSION",
  "CUSTOMER UNSUPPRESSION",
  "EMPLOYEE REASSIGNMENT",
  "NEW CLASSIC FOODS",
  "EQUIPMENT CHANGE REQUEST",
  "NEW MICRO MARKET",
  "NEW DATA CHANGE",
  "NEW PAYER",
  "FULL ROUTE SWAP",
  "MASS REQUEST",
  "NEW DRIVER REQUEST",
  "NEW EMPLOYEE REASSIGNMENT",
] as const;

export type RequestModule = (typeof REQUEST_MODULE_OPTIONS)[number];

export const DEFAULT_REQUEST_MODULE: RequestModule = "NEW DATA CHANGE";
